site_name: Prosthetic Hand Control
site_description: EMG/EEG data collection & docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - toc.follow
    - content.code.copy
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]
          options:
            docstring_style: google
            show_source: false
            members_order: source
            show_root_heading: true
            show_root_toc_entry: true
            show_object_full_path: false
            group_by_category: true
            heading_level: 2
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference:
      - Recording: api/recording.md
      - Configuration: api/config.md
      - Utilities:
          - Processing: api/util/processing.md
          - Filters: api/util/filters.md
          - Socket Handling: api/util/socket_handling.md
          - File Pathing: api/util/file_pathing.md
          - Data Validation: api/util/data_validation.md
          - Channel Alignment: api/util/channel_alignment.md
